version: "3"

services:
    frontend:
        container_name: reactapp
        build:
            context: ./frontend/gui/
            dockerfile: Dockerfile
        image: umairkhancis/reactapp
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/gui:/frontend/gui
        links: 
            - backend:backend
    backend:
        container_name: djangoapp
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: umairkhancis/djangoapp
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/backend
        links: 
            - mysql_database:mysql_database
        depends_on: 
            - mysql_database
        command: sh -c "
            python manage.py makemigrations
            && python manage.py migrate
            && python manage.py loaddata article_fixture.json
            && python manage.py runserver 0.0.0.0:8000
          "
    mysql_database:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: fullstackapp_db
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3308:3306"
    redis:
        image: sameersbn/redis:latest
        ports:
            - 8001:6379
    redisBanner:
        image: tenstartups/redis-commander
        command: --redis-host redis
        links:
            - redis:redis
        ports:
            - 8002:8081