version: "3"

services:
    frontend:
        container_name: reactapp
        build:
            context: ./frontend/gui/
            dockerfile: Dockerfile
        image: umairkhancis/reactapp
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/gui:/frontend/gui
        links: 
            - backend:backend
    backend:
        container_name: djangoapp
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: umairkhancis/djangoapp
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/backend
    redis:
        image: sameersbn/redis:latest
        ports:
            - 8001:6379
    redisBanner:
        image: tenstartups/redis-commander
        command: --redis-host redis
        links:
            - redis:redis
        ports:
            - 8002:8081